/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PassportIndexRouteImport } from './routes/passport.index'
import { Route as LandingIndexRouteImport } from './routes/landing.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as LandingRulesRouteImport } from './routes/landing.rules'
import { Route as LandingExperiencesRouteImport } from './routes/landing.experiences'
import { Route as LandingEventsRouteImport } from './routes/landing.events'
import { Route as LandingBrandsRouteImport } from './routes/landing.brands'
import { Route as LandingAboutRouteImport } from './routes/landing.about'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SiteRulesRouteImport } from './routes/_site.rules'
import { Route as SiteExperiencesRouteImport } from './routes/_site.experiences'
import { Route as SiteEventsRouteImport } from './routes/_site.events'
import { Route as SiteBrandsRouteImport } from './routes/_site.brands'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as AuthenticatedPassportRouteImport } from './routes/_authenticated/passport'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/passport/',
  path: '/passport/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRulesRoute = LandingRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LandingRoute,
} as any)
const LandingExperiencesRoute = LandingExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => LandingRoute,
} as any)
const LandingEventsRoute = LandingEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBrandsRoute = LandingBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SiteRulesRoute = SiteRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExperiencesRoute = SiteExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsRoute = SiteEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBrandsRoute = SiteBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedPassportRoute = AuthenticatedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/landing': typeof LandingRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/about': typeof SiteAboutRoute
  '/brands': typeof SiteBrandsRoute
  '/events': typeof SiteEventsRoute
  '/experiences': typeof SiteExperiencesRoute
  '/rules': typeof SiteRulesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/landing/about': typeof LandingAboutRoute
  '/landing/brands': typeof LandingBrandsRoute
  '/landing/events': typeof LandingEventsRoute
  '/landing/experiences': typeof LandingExperiencesRoute
  '/landing/rules': typeof LandingRulesRoute
  '/p/$code': typeof PCodeRoute
  '/landing/': typeof LandingIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/passport': typeof PassportIndexRoute
  '/about': typeof SiteAboutRoute
  '/brands': typeof SiteBrandsRoute
  '/events': typeof SiteEventsRoute
  '/experiences': typeof SiteExperiencesRoute
  '/rules': typeof SiteRulesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/landing/about': typeof LandingAboutRoute
  '/landing/brands': typeof LandingBrandsRoute
  '/landing/events': typeof LandingEventsRoute
  '/landing/experiences': typeof LandingExperiencesRoute
  '/landing/rules': typeof LandingRulesRoute
  '/p/$code': typeof PCodeRoute
  '/landing': typeof LandingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/landing': typeof LandingRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/passport': typeof AuthenticatedPassportRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/brands': typeof SiteBrandsRoute
  '/_site/events': typeof SiteEventsRoute
  '/_site/experiences': typeof SiteExperiencesRoute
  '/_site/rules': typeof SiteRulesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/landing/about': typeof LandingAboutRoute
  '/landing/brands': typeof LandingBrandsRoute
  '/landing/events': typeof LandingEventsRoute
  '/landing/experiences': typeof LandingExperiencesRoute
  '/landing/rules': typeof LandingRulesRoute
  '/p/$code': typeof PCodeRoute
  '/_site/': typeof SiteIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/passport/': typeof PassportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/admin'
    | '/discover'
    | '/leaderboard'
    | '/onboarding'
    | '/passport'
    | '/about'
    | '/brands'
    | '/events'
    | '/experiences'
    | '/rules'
    | '/auth/callback'
    | '/landing/about'
    | '/landing/brands'
    | '/landing/events'
    | '/landing/experiences'
    | '/landing/rules'
    | '/p/$code'
    | '/landing/'
    | '/passport/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/discover'
    | '/leaderboard'
    | '/onboarding'
    | '/passport'
    | '/about'
    | '/brands'
    | '/events'
    | '/experiences'
    | '/rules'
    | '/auth/callback'
    | '/landing/about'
    | '/landing/brands'
    | '/landing/events'
    | '/landing/experiences'
    | '/landing/rules'
    | '/p/$code'
    | '/landing'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/landing'
    | '/_authenticated/admin'
    | '/_authenticated/discover'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/passport'
    | '/_site/about'
    | '/_site/brands'
    | '/_site/events'
    | '/_site/experiences'
    | '/_site/rules'
    | '/auth/callback'
    | '/landing/about'
    | '/landing/brands'
    | '/landing/events'
    | '/landing/experiences'
    | '/landing/rules'
    | '/p/$code'
    | '/_site/'
    | '/landing/'
    | '/passport/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  PCodeRoute: typeof PCodeRoute
  PassportIndexRoute: typeof PassportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/passport'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/rules': {
      id: '/landing/rules'
      path: '/rules'
      fullPath: '/landing/rules'
      preLoaderRoute: typeof LandingRulesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/experiences': {
      id: '/landing/experiences'
      path: '/experiences'
      fullPath: '/landing/experiences'
      preLoaderRoute: typeof LandingExperiencesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/events': {
      id: '/landing/events'
      path: '/events'
      fullPath: '/landing/events'
      preLoaderRoute: typeof LandingEventsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/brands': {
      id: '/landing/brands'
      path: '/brands'
      fullPath: '/landing/brands'
      preLoaderRoute: typeof LandingBrandsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/landing/about': {
      id: '/landing/about'
      path: '/about'
      fullPath: '/landing/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/rules': {
      id: '/_site/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SiteRulesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/experiences': {
      id: '/_site/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof SiteExperiencesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events': {
      id: '/_site/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SiteEventsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/brands': {
      id: '/_site/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof SiteBrandsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/passport': {
      id: '/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPassportRoute: typeof AuthenticatedPassportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPassportRoute: AuthenticatedPassportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBrandsRoute: typeof SiteBrandsRoute
  SiteEventsRoute: typeof SiteEventsRoute
  SiteExperiencesRoute: typeof SiteExperiencesRoute
  SiteRulesRoute: typeof SiteRulesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBrandsRoute: SiteBrandsRoute,
  SiteEventsRoute: SiteEventsRoute,
  SiteExperiencesRoute: SiteExperiencesRoute,
  SiteRulesRoute: SiteRulesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingBrandsRoute: typeof LandingBrandsRoute
  LandingEventsRoute: typeof LandingEventsRoute
  LandingExperiencesRoute: typeof LandingExperiencesRoute
  LandingRulesRoute: typeof LandingRulesRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingBrandsRoute: LandingBrandsRoute,
  LandingEventsRoute: LandingEventsRoute,
  LandingExperiencesRoute: LandingExperiencesRoute,
  LandingRulesRoute: LandingRulesRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  PCodeRoute: PCodeRoute,
  PassportIndexRoute: PassportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
