/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as PassportIndexRouteImport } from './routes/passport.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as PassportAuthenticatedRouteImport } from './routes/passport._authenticated'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SiteSafetyRouteImport } from './routes/_site.safety'
import { Route as SiteRulesRouteImport } from './routes/_site.rules'
import { Route as SiteRefundPolicyRouteImport } from './routes/_site.refund-policy'
import { Route as SiteHowItWorksRouteImport } from './routes/_site.how-it-works'
import { Route as SiteExperiencesRouteImport } from './routes/_site.experiences'
import { Route as SiteEventsRouteImport } from './routes/_site.events'
import { Route as SiteBrandsRouteImport } from './routes/_site.brands'
import { Route as SiteApplyRouteImport } from './routes/_site.apply'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteEventsIndexRouteImport } from './routes/_site.events.index'
import { Route as PassportAuthenticatedPassportRouteImport } from './routes/passport._authenticated.passport'
import { Route as PassportAuthenticatedOnboardingRouteImport } from './routes/passport._authenticated.onboarding'
import { Route as PassportAuthenticatedLeaderboardRouteImport } from './routes/passport._authenticated.leaderboard'
import { Route as PassportAuthenticatedDiscoverRouteImport } from './routes/passport._authenticated.discover'
import { Route as PassportAuthenticatedAdminRouteImport } from './routes/passport._authenticated.admin'
import { Route as SiteEventsGoaSusegadRouteImport } from './routes/_site.events.goa-susegad'
import { Route as PassportAuthenticatedAdminAuditRouteImport } from './routes/passport._authenticated.admin_.audit'
import { Route as PassportAuthenticatedAdminActivityRouteImport } from './routes/passport._authenticated.admin_.activity'
import { Route as SiteEventsGoaSusegadRequestInviteRouteImport } from './routes/_site.events.goa-susegad_.request-invite'

const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassportRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const PassportAuthenticatedRoute = PassportAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => PassportRoute,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SiteSafetyRoute = SiteSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRulesRoute = SiteRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRefundPolicyRoute = SiteRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHowItWorksRoute = SiteHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExperiencesRoute = SiteExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsRoute = SiteEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBrandsRoute = SiteBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SiteRoute,
} as any)
const SiteApplyRoute = SiteApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventsIndexRoute = SiteEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteEventsRoute,
} as any)
const PassportAuthenticatedPassportRoute =
  PassportAuthenticatedPassportRouteImport.update({
    id: '/passport',
    path: '/passport',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const PassportAuthenticatedOnboardingRoute =
  PassportAuthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const PassportAuthenticatedLeaderboardRoute =
  PassportAuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const PassportAuthenticatedDiscoverRoute =
  PassportAuthenticatedDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const PassportAuthenticatedAdminRoute =
  PassportAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const SiteEventsGoaSusegadRoute = SiteEventsGoaSusegadRouteImport.update({
  id: '/goa-susegad',
  path: '/goa-susegad',
  getParentRoute: () => SiteEventsRoute,
} as any)
const PassportAuthenticatedAdminAuditRoute =
  PassportAuthenticatedAdminAuditRouteImport.update({
    id: '/admin_/audit',
    path: '/admin/audit',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const PassportAuthenticatedAdminActivityRoute =
  PassportAuthenticatedAdminActivityRouteImport.update({
    id: '/admin_/activity',
    path: '/admin/activity',
    getParentRoute: () => PassportAuthenticatedRoute,
  } as any)
const SiteEventsGoaSusegadRequestInviteRoute =
  SiteEventsGoaSusegadRequestInviteRouteImport.update({
    id: '/goa-susegad_/request-invite',
    path: '/goa-susegad/request-invite',
    getParentRoute: () => SiteEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/partner': typeof PartnerRoute
  '/passport': typeof PassportRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/apply': typeof SiteApplyRoute
  '/brands': typeof SiteBrandsRoute
  '/events': typeof SiteEventsRouteWithChildren
  '/experiences': typeof SiteExperiencesRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/rules': typeof SiteRulesRoute
  '/safety': typeof SiteSafetyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$code': typeof PCodeRoute
  '/passport/': typeof PassportIndexRoute
  '/events/goa-susegad': typeof SiteEventsGoaSusegadRoute
  '/passport/admin': typeof PassportAuthenticatedAdminRoute
  '/passport/discover': typeof PassportAuthenticatedDiscoverRoute
  '/passport/leaderboard': typeof PassportAuthenticatedLeaderboardRoute
  '/passport/onboarding': typeof PassportAuthenticatedOnboardingRoute
  '/passport/passport': typeof PassportAuthenticatedPassportRoute
  '/events/': typeof SiteEventsIndexRoute
  '/events/goa-susegad/request-invite': typeof SiteEventsGoaSusegadRequestInviteRoute
  '/passport/admin/activity': typeof PassportAuthenticatedAdminActivityRoute
  '/passport/admin/audit': typeof PassportAuthenticatedAdminAuditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/partner': typeof PartnerRoute
  '/about': typeof SiteAboutRoute
  '/apply': typeof SiteApplyRoute
  '/brands': typeof SiteBrandsRoute
  '/experiences': typeof SiteExperiencesRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/refund-policy': typeof SiteRefundPolicyRoute
  '/rules': typeof SiteRulesRoute
  '/safety': typeof SiteSafetyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$code': typeof PCodeRoute
  '/passport': typeof PassportIndexRoute
  '/': typeof SiteIndexRoute
  '/events/goa-susegad': typeof SiteEventsGoaSusegadRoute
  '/passport/admin': typeof PassportAuthenticatedAdminRoute
  '/passport/discover': typeof PassportAuthenticatedDiscoverRoute
  '/passport/leaderboard': typeof PassportAuthenticatedLeaderboardRoute
  '/passport/onboarding': typeof PassportAuthenticatedOnboardingRoute
  '/passport/passport': typeof PassportAuthenticatedPassportRoute
  '/events': typeof SiteEventsIndexRoute
  '/events/goa-susegad/request-invite': typeof SiteEventsGoaSusegadRequestInviteRoute
  '/passport/admin/activity': typeof PassportAuthenticatedAdminActivityRoute
  '/passport/admin/audit': typeof PassportAuthenticatedAdminAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/partner': typeof PartnerRoute
  '/passport': typeof PassportRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/apply': typeof SiteApplyRoute
  '/_site/brands': typeof SiteBrandsRoute
  '/_site/events': typeof SiteEventsRouteWithChildren
  '/_site/experiences': typeof SiteExperiencesRoute
  '/_site/how-it-works': typeof SiteHowItWorksRoute
  '/_site/refund-policy': typeof SiteRefundPolicyRoute
  '/_site/rules': typeof SiteRulesRoute
  '/_site/safety': typeof SiteSafetyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$code': typeof PCodeRoute
  '/passport/_authenticated': typeof PassportAuthenticatedRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/passport/': typeof PassportIndexRoute
  '/_site/events/goa-susegad': typeof SiteEventsGoaSusegadRoute
  '/passport/_authenticated/admin': typeof PassportAuthenticatedAdminRoute
  '/passport/_authenticated/discover': typeof PassportAuthenticatedDiscoverRoute
  '/passport/_authenticated/leaderboard': typeof PassportAuthenticatedLeaderboardRoute
  '/passport/_authenticated/onboarding': typeof PassportAuthenticatedOnboardingRoute
  '/passport/_authenticated/passport': typeof PassportAuthenticatedPassportRoute
  '/_site/events/': typeof SiteEventsIndexRoute
  '/_site/events/goa-susegad_/request-invite': typeof SiteEventsGoaSusegadRequestInviteRoute
  '/passport/_authenticated/admin_/activity': typeof PassportAuthenticatedAdminActivityRoute
  '/passport/_authenticated/admin_/audit': typeof PassportAuthenticatedAdminAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/partner'
    | '/passport'
    | '/about'
    | '/apply'
    | '/brands'
    | '/events'
    | '/experiences'
    | '/how-it-works'
    | '/refund-policy'
    | '/rules'
    | '/safety'
    | '/auth/callback'
    | '/p/$code'
    | '/passport/'
    | '/events/goa-susegad'
    | '/passport/admin'
    | '/passport/discover'
    | '/passport/leaderboard'
    | '/passport/onboarding'
    | '/passport/passport'
    | '/events/'
    | '/events/goa-susegad/request-invite'
    | '/passport/admin/activity'
    | '/passport/admin/audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/partner'
    | '/about'
    | '/apply'
    | '/brands'
    | '/experiences'
    | '/how-it-works'
    | '/refund-policy'
    | '/rules'
    | '/safety'
    | '/auth/callback'
    | '/p/$code'
    | '/passport'
    | '/'
    | '/events/goa-susegad'
    | '/passport/admin'
    | '/passport/discover'
    | '/passport/leaderboard'
    | '/passport/onboarding'
    | '/passport/passport'
    | '/events'
    | '/events/goa-susegad/request-invite'
    | '/passport/admin/activity'
    | '/passport/admin/audit'
  id:
    | '__root__'
    | '/_site'
    | '/auth'
    | '/partner'
    | '/passport'
    | '/_site/about'
    | '/_site/apply'
    | '/_site/brands'
    | '/_site/events'
    | '/_site/experiences'
    | '/_site/how-it-works'
    | '/_site/refund-policy'
    | '/_site/rules'
    | '/_site/safety'
    | '/auth/callback'
    | '/p/$code'
    | '/passport/_authenticated'
    | '/_site/'
    | '/passport/'
    | '/_site/events/goa-susegad'
    | '/passport/_authenticated/admin'
    | '/passport/_authenticated/discover'
    | '/passport/_authenticated/leaderboard'
    | '/passport/_authenticated/onboarding'
    | '/passport/_authenticated/passport'
    | '/_site/events/'
    | '/_site/events/goa-susegad_/request-invite'
    | '/passport/_authenticated/admin_/activity'
    | '/passport/_authenticated/admin_/audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PartnerRoute: typeof PartnerRoute
  PassportRoute: typeof PassportRouteWithChildren
  PCodeRoute: typeof PCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof PassportRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/passport/_authenticated': {
      id: '/passport/_authenticated'
      path: ''
      fullPath: '/passport'
      preLoaderRoute: typeof PassportAuthenticatedRouteImport
      parentRoute: typeof PassportRoute
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/safety': {
      id: '/_site/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SiteSafetyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/rules': {
      id: '/_site/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SiteRulesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/refund-policy': {
      id: '/_site/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof SiteRefundPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/how-it-works': {
      id: '/_site/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof SiteHowItWorksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/experiences': {
      id: '/_site/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof SiteExperiencesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events': {
      id: '/_site/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SiteEventsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/brands': {
      id: '/_site/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof SiteBrandsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/apply': {
      id: '/_site/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof SiteApplyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/events/': {
      id: '/_site/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof SiteEventsIndexRouteImport
      parentRoute: typeof SiteEventsRoute
    }
    '/passport/_authenticated/passport': {
      id: '/passport/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport/passport'
      preLoaderRoute: typeof PassportAuthenticatedPassportRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/passport/_authenticated/onboarding': {
      id: '/passport/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/passport/onboarding'
      preLoaderRoute: typeof PassportAuthenticatedOnboardingRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/passport/_authenticated/leaderboard': {
      id: '/passport/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/passport/leaderboard'
      preLoaderRoute: typeof PassportAuthenticatedLeaderboardRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/passport/_authenticated/discover': {
      id: '/passport/_authenticated/discover'
      path: '/discover'
      fullPath: '/passport/discover'
      preLoaderRoute: typeof PassportAuthenticatedDiscoverRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/passport/_authenticated/admin': {
      id: '/passport/_authenticated/admin'
      path: '/admin'
      fullPath: '/passport/admin'
      preLoaderRoute: typeof PassportAuthenticatedAdminRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/_site/events/goa-susegad': {
      id: '/_site/events/goa-susegad'
      path: '/goa-susegad'
      fullPath: '/events/goa-susegad'
      preLoaderRoute: typeof SiteEventsGoaSusegadRouteImport
      parentRoute: typeof SiteEventsRoute
    }
    '/passport/_authenticated/admin_/audit': {
      id: '/passport/_authenticated/admin_/audit'
      path: '/admin/audit'
      fullPath: '/passport/admin/audit'
      preLoaderRoute: typeof PassportAuthenticatedAdminAuditRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/passport/_authenticated/admin_/activity': {
      id: '/passport/_authenticated/admin_/activity'
      path: '/admin/activity'
      fullPath: '/passport/admin/activity'
      preLoaderRoute: typeof PassportAuthenticatedAdminActivityRouteImport
      parentRoute: typeof PassportAuthenticatedRoute
    }
    '/_site/events/goa-susegad_/request-invite': {
      id: '/_site/events/goa-susegad_/request-invite'
      path: '/goa-susegad/request-invite'
      fullPath: '/events/goa-susegad/request-invite'
      preLoaderRoute: typeof SiteEventsGoaSusegadRequestInviteRouteImport
      parentRoute: typeof SiteEventsRoute
    }
  }
}

interface SiteEventsRouteChildren {
  SiteEventsGoaSusegadRoute: typeof SiteEventsGoaSusegadRoute
  SiteEventsIndexRoute: typeof SiteEventsIndexRoute
  SiteEventsGoaSusegadRequestInviteRoute: typeof SiteEventsGoaSusegadRequestInviteRoute
}

const SiteEventsRouteChildren: SiteEventsRouteChildren = {
  SiteEventsGoaSusegadRoute: SiteEventsGoaSusegadRoute,
  SiteEventsIndexRoute: SiteEventsIndexRoute,
  SiteEventsGoaSusegadRequestInviteRoute:
    SiteEventsGoaSusegadRequestInviteRoute,
}

const SiteEventsRouteWithChildren = SiteEventsRoute._addFileChildren(
  SiteEventsRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteApplyRoute: typeof SiteApplyRoute
  SiteBrandsRoute: typeof SiteBrandsRoute
  SiteEventsRoute: typeof SiteEventsRouteWithChildren
  SiteExperiencesRoute: typeof SiteExperiencesRoute
  SiteHowItWorksRoute: typeof SiteHowItWorksRoute
  SiteRefundPolicyRoute: typeof SiteRefundPolicyRoute
  SiteRulesRoute: typeof SiteRulesRoute
  SiteSafetyRoute: typeof SiteSafetyRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteApplyRoute: SiteApplyRoute,
  SiteBrandsRoute: SiteBrandsRoute,
  SiteEventsRoute: SiteEventsRouteWithChildren,
  SiteExperiencesRoute: SiteExperiencesRoute,
  SiteHowItWorksRoute: SiteHowItWorksRoute,
  SiteRefundPolicyRoute: SiteRefundPolicyRoute,
  SiteRulesRoute: SiteRulesRoute,
  SiteSafetyRoute: SiteSafetyRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PassportAuthenticatedRouteChildren {
  PassportAuthenticatedAdminRoute: typeof PassportAuthenticatedAdminRoute
  PassportAuthenticatedDiscoverRoute: typeof PassportAuthenticatedDiscoverRoute
  PassportAuthenticatedLeaderboardRoute: typeof PassportAuthenticatedLeaderboardRoute
  PassportAuthenticatedOnboardingRoute: typeof PassportAuthenticatedOnboardingRoute
  PassportAuthenticatedPassportRoute: typeof PassportAuthenticatedPassportRoute
  PassportAuthenticatedAdminActivityRoute: typeof PassportAuthenticatedAdminActivityRoute
  PassportAuthenticatedAdminAuditRoute: typeof PassportAuthenticatedAdminAuditRoute
}

const PassportAuthenticatedRouteChildren: PassportAuthenticatedRouteChildren = {
  PassportAuthenticatedAdminRoute: PassportAuthenticatedAdminRoute,
  PassportAuthenticatedDiscoverRoute: PassportAuthenticatedDiscoverRoute,
  PassportAuthenticatedLeaderboardRoute: PassportAuthenticatedLeaderboardRoute,
  PassportAuthenticatedOnboardingRoute: PassportAuthenticatedOnboardingRoute,
  PassportAuthenticatedPassportRoute: PassportAuthenticatedPassportRoute,
  PassportAuthenticatedAdminActivityRoute:
    PassportAuthenticatedAdminActivityRoute,
  PassportAuthenticatedAdminAuditRoute: PassportAuthenticatedAdminAuditRoute,
}

const PassportAuthenticatedRouteWithChildren =
  PassportAuthenticatedRoute._addFileChildren(
    PassportAuthenticatedRouteChildren,
  )

interface PassportRouteChildren {
  PassportAuthenticatedRoute: typeof PassportAuthenticatedRouteWithChildren
  PassportIndexRoute: typeof PassportIndexRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportAuthenticatedRoute: PassportAuthenticatedRouteWithChildren,
  PassportIndexRoute: PassportIndexRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PartnerRoute: PartnerRoute,
  PassportRoute: PassportRouteWithChildren,
  PCodeRoute: PCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
